export const productContants = {
  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_FAILED: "GET_PRODUCT_FAILED",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAILED: "ADD_PRODUCT_FAILED",
  GET_TAB_SESSION_SUCCESS: "GET_TAB_SESSION_SUCCESS",
};

export const authContants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT_SUCCES: "LOGOUT_SUCCES",
};

export const tabContants = {
  GET_TAB_REQUEST: "GET_TAB_REQUEST",
  GET_TAB_SUCCESS: "GET_TAB_SUCCESS",
  GET_TAB_FAILED: "GET_TAB_FAILED",
  ADD_TAB_SUCCESS: "ADD_TAB_SUCCESS",
};

export const backendContants = {
  GET_ALL_BACKEND_SUCCESS: "GET_ALL_BACKEND_SUCCESS",
  GET_ALL_BACKEND_ACTIVE: "GET_ALL_BACKEND_ACTIVE",
  ADD_BACKEND_SUCCESS: "ADD_BACKEND_SUCCESS",
};

export const roleContants = {
  ADD_ROLE_SUCCESS: "ADD_ROLE_SUCCESS",
  GET_ALL_ROLE_SUCCESS: "GET_ALL_ROLE_SUCCESS",
  GET_ALL_ACTIVE_ROLE: "GET_ALL_ACTIVE_ROLE",
};

export const userContants = {
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  GET_ALL_USER_SUCCESS: "GET_ALL_USER_SUCCESS",
};

export const SHOWLOADING = "SHOWLOADING";
export const HIDELOADING = "HIDELOADING";
